# escape=`
FROM plugins/base:windows-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Codedeploy" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release\drone-codedeploy.exe c:\drone-codedeploy.exe
ENTRYPOINT [ "c:\\drone-codedeploy.exe" ]
